In [1]:
import numpy as np
from oars.matrices import getFull, getMfromWCholesky

In [2]:
Zt, Wt = getFull(2)
Zt

array([[ 2., -2.],
       [-2.,  2.]])

In [3]:
M = np.block([[Zt, np.zeros((2,2))], [np.zeros((2,2)), Zt]])
M

array([[ 2., -2.,  0.,  0.],
       [-2.,  2.,  0.,  0.],
       [ 0.,  0.,  2., -2.],
       [ 0.,  0., -2.,  2.]])

In [4]:
np.linalg.eigh(M)

EighResult(eigenvalues=array([0., 0., 4., 4.]), eigenvectors=array([[-0.70710678, -0.        ,  0.        , -0.70710678],
       [-0.70710678, -0.        ,  0.        ,  0.70710678],
       [-0.        , -0.70710678, -0.70710678,  0.        ],
       [-0.        , -0.70710678,  0.70710678,  0.        ]]))

In [5]:
Ba = np.array([[1, 0, 0, 0], [0,0,1,0]])
Zt @ Ba

array([[ 2.,  0., -2.,  0.],
       [-2.,  0.,  2.,  0.]])

In [6]:
Lt = np.array([[0,0], [2, 0]])
Lt @Ba

array([[0, 0, 0, 0],
       [2, 0, 0, 0]])

In [7]:
Mt = np.array([1, -1])
Mt @ Ba

array([ 1,  0, -1,  0])

In [8]:
(Mt @ Ba).T

array([ 1,  0, -1,  0])

In [9]:
Z, W = getFull(3)
M = getMfromWCholesky(W)
M

array([[-1.22474487,  1.22474487,  0.        ],
       [-0.70710678, -0.70710678,  1.41421356]])

In [10]:
(3/2)**0.5

1.224744871391589

In [13]:
from sympy import symbols, Matrix, eye, zeros

def calculate_KT_LK(L1_dim, L2_dim, L3_dim, permutation):
    """
    Calculates K^T L K where:
    - K is a permutation matrix formed from unit vectors e_i.
    - L is a block diagonal matrix with lower triangular matrices L1, L2, L3.

    Args:
        L1_dim (int): Dimension of L1.
        L2_dim (int): Dimension of L2.
        L3_dim (int): Dimension of L3.
        permutation (list): List of indices representing the permutation of unit vectors.

    Returns:
        sympy.Matrix: The result of K^T L K.
    """

    total_dim = L1_dim + L2_dim + L3_dim
    K = Matrix.zeros(total_dim, total_dim)
    L = Matrix.zeros(total_dim, total_dim)

    # Create permutation matrix K
    for i, index in enumerate(permutation):
        K[i, index - 1] = 1  # Subtract 1 because indices are 1-based

    # Create block diagonal matrix L
    L1 = Matrix(L1_dim, L1_dim, lambda i, j: symbols(f'L1_{i}_{j}') if i > j else 0)
    L2 = Matrix(L2_dim, L2_dim, lambda i, j: symbols(f'L2_{i}_{j}') if i > j else 0)
    L3 = Matrix(L3_dim, L3_dim, lambda i, j: symbols(f'L3_{i}_{j}') if i > j else 0)

    L[:L1_dim, :L1_dim] = L1
    L[L1_dim:L1_dim + L2_dim, L1_dim:L1_dim + L2_dim] = L2
    L[L1_dim + L2_dim:, L1_dim + L2_dim:] = L3

    # Calculate K^T L K
    KT = K.T
    result = KT * L * K

    return result

# Example usage:
L1_dim = 3
L2_dim = 3
L3_dim = 2
permutation = [1, 3, 7, 2, 5, 8, 4, 6]

result = calculate_KT_LK(L1_dim, L2_dim, L3_dim, permutation)
print(result)

Matrix([[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [L1_1_0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, L2_1_0, 0, 0, 0, 0, 0, 0], [0, 0, 0, L3_1_0, 0, 0, 0, 0], [L1_2_0, 0, L1_2_1, 0, 0, 0, 0, 0], [0, L2_2_0, 0, 0, L2_2_1, 0, 0, 0]])


In [14]:
result

Matrix([
[     0,      0,      0,      0,      0, 0, 0, 0],
[     0,      0,      0,      0,      0, 0, 0, 0],
[L1_1_0,      0,      0,      0,      0, 0, 0, 0],
[     0,      0,      0,      0,      0, 0, 0, 0],
[     0, L2_1_0,      0,      0,      0, 0, 0, 0],
[     0,      0,      0, L3_1_0,      0, 0, 0, 0],
[L1_2_0,      0, L1_2_1,      0,      0, 0, 0, 0],
[     0, L2_2_0,      0,      0, L2_2_1, 0, 0, 0]])